### ISSUE TITLE
Position for "bold arc = median"

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/odmm-mbei-dashboard#12]
I think the "bold arc = median" should be positioned somewhere else. It is difficult to read there. 
![image](https://user-images.githubusercontent.com/18112596/105928251-33820d80-600b-11eb-8f9d-b8a4d075e2a6.png)

**Comment by arky** [comment]
That's part of the original design, so I'll leave unchanged for now. Feel free to send a PR.
