### ISSUE TITLE
The full title should pop up when hover on icon

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/odmm-mbei-dashboard#13]
When hover on the icon, the full title should show up. For example, the Payment => Informal charges. Also,  I think payment conveys a positive meaning while informal changes seems to be another word of corruption.
![image](https://user-images.githubusercontent.com/18112596/105929125-87d9bd00-600c-11eb-8526-50b69331ce80.png)
![image](https://user-images.githubusercontent.com/18112596/105929360-046c9b80-600d-11eb-982e-a4fa52656a7f.png)

**Comment by arky** [comment]
That's part of the original design, so I'll leave it unchanged for now. Feel free to send a PR.

**Comment by arky** [comment]
Closing this issue as it pertains to the original design of the dashboard. The current task is to update the dashboard for 2020 data not design changes.
