### ISSUE TITLE
Graph does not change when I click on Township bottom to reset the graph

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/odmm-mbei-dashboard#14]
When I compared two different township, I clicked on the township bottom to reset the graph. But it doesn't change. 

![image](https://user-images.githubusercontent.com/18112596/105929693-c58b1580-600d-11eb-9afe-94eb31323ef9.png)

**Comment by arky** [comment]
Related to #6 and #11

**Comment by arky** [comment]
Fixed in https://github.com/OpenDevelopmentMekong/odmm-mbei-dashboard/commit/87a5f86a3a9c47eb4d793e46e985fa75e141b14a
