### ISSUE TITLE
to update "Download the data here"

### ISSUE THREAD

**Issue by lekhine** [OpenDevelopmentMekong/odmm-mbei-dashboard#16]
@arky 
The existing data are 2019 data and need to update with 2020 data.
https://opendevelopmentmyanmar.net/mbei
![image](https://user-images.githubusercontent.com/54614525/106109410-e5d6e380-6177-11eb-9d9c-637bcc51c5d3.png)

**Comment by arky** [comment]
Ma @lekhine The new MBEI dashboard is on our pre-production server only, once all the issues are resolved we'll update it on main server. 
 
https://pp.opendevelopmentmyanmar.net/mbei

The new  download section looks like this. 
![image](https://user-images.githubusercontent.com/808895/106139296-d53a6380-619f-11eb-8e13-84e79308a7c5.png)
