### ISSUE TITLE
Update MBEI 2019 Data 

### ISSUE THREAD

**Issue by arky** [OpenDevelopmentMekong/odmm-mbei-dashboard#8]
The MBEI 2019 data needs to be updated.  @villpe to send new dataset

**Comment by villpe** [comment]
The MBEI 2019 data should be the same as the data on the existing dashboard and there is no need to change it. I did change it in the part of the code that says 2019. But it didn't seem to have any effect. I'm attaching both 2019 and 2020 dashboard data excel files here. 
[mbei2019_dashboard_data 20210105.xlsx](https://github.com/OpenDevelopmentMekong/odmm-mbei-dashboard/files/5773645/mbei2019_dashboard_data.20210105.xlsx)
[mbei2020_dashboard_data 20210105.xlsx](https://github.com/OpenDevelopmentMekong/odmm-mbei-dashboard/files/5773646/mbei2020_dashboard_data.20210105.xlsx)

**Comment by arky** [comment]
Possibly related to bug #7 
MBEI data is present in (variables.js)[https://github.com/OpenDevelopmentMekong/odmm-mbei-dashboard/blob/master/variables.js]
